const transResources = {
  ru: {
    translation: {
      "search":'Поиск',
      "search1":'Поиск',
      "p":'О портале',
      "1r":'Данный портал содержит информацию о писателях Беларуси.',
      "2r":'На главной странице содержится информация о портале, деятеле дня и команде разработчиков.',
      "3r":'Также портал содержит персональную страницу каждого писателя.',
      "4r":'Описание деятеля содержит: биографию, фотогалерею с фотографиями писателя и его работ,',
      "5r":'видео на YouTube о деятеле и место его основной деятельности на карте.',
      "H":'На главную',
      "W":'Вики',
      "Wr":'Писатели',
      "CM":'Деятель дня',
      "VM":'Видео о писателе',
      "PM":'Место деятельности писателя',
      "LM":'Жизнь и творчество',
      "VB":'Видео о писателе',
      "PB":'Место деятельности писателя',
      "LB":'Жизнь и творчество',
      "VK":'Видео о писателе',
      "PK":'Место деятельности писателя',
      "LK":'Жизнь и творчество',
      "VKR":'Видео о писателе',
      "PKR":'Место деятельности писателя',
      "LKR":'Жизнь и творчество',
      "VKU":'Видео о писателе',
      "PKU":'Место деятельности писателя',
      "LKU":'Жизнь и творчество',
      "VT":'Видео о писателе',
      "PT":'Место деятельности писателя',
      "LT":'Жизнь и творчество',
      "Writers":'Писатели',
      "Learn":'Узнать больше',
      "Dasha":'Зайцева Дарья',
      "Sasha":'Александр Струков',
      "Sergey":'Витушко Сергей',
      "Team":'Команда'
    }
  },
  en: {
    translation: {
      "search":'Search',
      "search1":'Search',
      "p":'About portal',
      "1r":'This portal contains information about belarusian writers',
      "2r":'On the main page contains information about portal, writer of the day and the developers team.',
      "3r":'Portal also contains personal page of every writer.',
      "4r":'Description of the writer contains: biography, photo gallery, with writer’s and his oeuvre’s photos,',
      "5r":'Video on YouTube and the place of his main activity on the map.',
      "H":'Home',
      "W":'Wiki',
      "Wr":'Writers',
      "CM":'Creator of the day',
      "VM":'Video about the writer',
      "PM":'Place of activity',
      "LM":'Live and creativity',
      "VB":'Video about the writer',
      "PB":'Place of activity',
      "LB":'Live and creativity',
      "VK":'Video about the writer',
      "PK":'Place of activity',
      "LK":'Live and creativity',
      "VKR":'Video about the writer',
      "PKR":'Place of activity',
      "LKR":'Live and creativity',
      "VKU":'Video about the writer',
      "PKU":'Place of activity',
      "LKU":'Live and creativity',
      "VT":'Video about the writer',
      "PT":'Place of activity',
      "LT":'Live and creativity',
      "Writers":'Writers',
      "Learn":'Learn more',
      "Dasha":'Zaitsava Darya',
      "Sasha":'Alexandr Strukov',
      "Sergey":'Vitushko Sergey',
      "Team":'Team'
    }
  }
};

export default transResources;